services:
  db:
    image: postgres:16-alpine
    container_name: fpl-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-fpl}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fplpassword}
      POSTGRES_DB: ${POSTGRES_DB:-fpldb}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-fpl} -d ${POSTGRES_DB:-fpldb}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fpl-app
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-fpl}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fplpassword}
      POSTGRES_DB: ${POSTGRES_DB:-fpldb}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "-u", "scripts/db_check.py"]

volumes:
  pgdata:

