"""Create gameweek history tables for all seasons

Revision ID: 11df647a6578
Revises: 2692fb6146b7
Create Date: 2025-08-12 13:37:57.236520

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11df647a6578"
down_revision: Union[str, Sequence[str], None] = "2692fb6146b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "player_gameweek_history_2016_17",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("name", sa.String()),
        sa.Column("assists", sa.BigInteger()),
        sa.Column("attempted_passes", sa.BigInteger()),
        sa.Column("big_chances_created", sa.BigInteger()),
        sa.Column("big_chances_missed", sa.BigInteger()),
        sa.Column("bonus", sa.BigInteger()),
        sa.Column("bps", sa.BigInteger()),
        sa.Column("clean_sheets", sa.BigInteger()),
        sa.Column("clearances_blocks_interceptions", sa.BigInteger()),
        sa.Column("completed_passes", sa.BigInteger()),
        sa.Column("creativity", sa.Float()),
        sa.Column("dribbles", sa.BigInteger()),
        sa.Column("ea_index", sa.BigInteger()),
        sa.Column("element", sa.BigInteger()),
        sa.Column("errors_leading_to_goal", sa.BigInteger()),
        sa.Column("errors_leading_to_goal_attempt", sa.BigInteger()),
        sa.Column("fixture", sa.BigInteger()),
        sa.Column("fouls", sa.BigInteger()),
        sa.Column("goals_conceded", sa.BigInteger()),
        sa.Column("goals_scored", sa.BigInteger()),
        sa.Column("ict_index", sa.Float()),
        sa.Column("influence", sa.Float()),
        sa.Column("key_passes", sa.BigInteger()),
        sa.Column("kickoff_time", sa.String()),
        sa.Column("kickoff_time_formatted", sa.String()),
        sa.Column("loaned_in", sa.BigInteger()),
        sa.Column("loaned_out", sa.BigInteger()),
        sa.Column("minutes", sa.BigInteger()),
        sa.Column("offside", sa.BigInteger()),
        sa.Column("open_play_crosses", sa.BigInteger()),
        sa.Column("opponent_team", sa.BigInteger()),
        sa.Column("own_goals", sa.BigInteger()),
        sa.Column("penalties_conceded", sa.BigInteger()),
        sa.Column("penalties_missed", sa.BigInteger()),
        sa.Column("penalties_saved", sa.BigInteger()),
        sa.Column("recoveries", sa.BigInteger()),
        sa.Column("red_cards", sa.BigInteger()),
        sa.Column("round", sa.BigInteger()),
        sa.Column("saves", sa.BigInteger()),
        sa.Column("selected", sa.BigInteger()),
        sa.Column("tackled", sa.BigInteger()),
        sa.Column("tackles", sa.BigInteger()),
        sa.Column("target_missed", sa.BigInteger()),
        sa.Column("team_a_score", sa.BigInteger()),
        sa.Column("team_h_score", sa.BigInteger()),
        sa.Column("threat", sa.BigInteger()),
        sa.Column("total_points", sa.BigInteger()),
        sa.Column("transfers_balance", sa.BigInteger()),
        sa.Column("transfers_in", sa.BigInteger()),
        sa.Column("transfers_out", sa.BigInteger()),
        sa.Column("value", sa.BigInteger()),
        sa.Column("was_home", sa.Boolean()),
        sa.Column("winning_goals", sa.BigInteger()),
        sa.Column("yellow_cards", sa.BigInteger()),
        sa.Column("GW", sa.BigInteger()),
    )
    op.create_table(
        "player_gameweek_history_2017_18",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("name", sa.String()),
        sa.Column("assists", sa.BigInteger()),
        sa.Column("attempted_passes", sa.BigInteger()),
        sa.Column("big_chances_created", sa.BigInteger()),
        sa.Column("big_chances_missed", sa.BigInteger()),
        sa.Column("bonus", sa.BigInteger()),
        sa.Column("bps", sa.BigInteger()),
        sa.Column("clean_sheets", sa.BigInteger()),
        sa.Column("clearances_blocks_interceptions", sa.BigInteger()),
        sa.Column("completed_passes", sa.BigInteger()),
        sa.Column("creativity", sa.Float()),
        sa.Column("dribbles", sa.BigInteger()),
        sa.Column("ea_index", sa.BigInteger()),
        sa.Column("element", sa.BigInteger()),
        sa.Column("errors_leading_to_goal", sa.BigInteger()),
        sa.Column("errors_leading_to_goal_attempt", sa.BigInteger()),
        sa.Column("fixture", sa.BigInteger()),
        sa.Column("fouls", sa.BigInteger()),
        sa.Column("goals_conceded", sa.BigInteger()),
        sa.Column("goals_scored", sa.BigInteger()),
        sa.Column("ict_index", sa.Float()),
        sa.Column("influence", sa.Float()),
        sa.Column("key_passes", sa.BigInteger()),
        sa.Column("kickoff_time", sa.String()),
        sa.Column("kickoff_time_formatted", sa.String()),
        sa.Column("loaned_in", sa.BigInteger()),
        sa.Column("loaned_out", sa.BigInteger()),
        sa.Column("minutes", sa.BigInteger()),
        sa.Column("offside", sa.BigInteger()),
        sa.Column("open_play_crosses", sa.BigInteger()),
        sa.Column("opponent_team", sa.BigInteger()),
        sa.Column("own_goals", sa.BigInteger()),
        sa.Column("penalties_conceded", sa.BigInteger()),
        sa.Column("penalties_missed", sa.BigInteger()),
        sa.Column("penalties_saved", sa.BigInteger()),
        sa.Column("recoveries", sa.BigInteger()),
        sa.Column("red_cards", sa.BigInteger()),
        sa.Column("round", sa.BigInteger()),
        sa.Column("saves", sa.BigInteger()),
        sa.Column("selected", sa.BigInteger()),
        sa.Column("tackled", sa.BigInteger()),
        sa.Column("tackles", sa.BigInteger()),
        sa.Column("target_missed", sa.BigInteger()),
        sa.Column("team_a_score", sa.BigInteger()),
        sa.Column("team_h_score", sa.BigInteger()),
        sa.Column("threat", sa.BigInteger()),
        sa.Column("total_points", sa.BigInteger()),
        sa.Column("transfers_balance", sa.BigInteger()),
        sa.Column("transfers_in", sa.BigInteger()),
        sa.Column("transfers_out", sa.BigInteger()),
        sa.Column("value", sa.BigInteger()),
        sa.Column("was_home", sa.Boolean()),
        sa.Column("winning_goals", sa.BigInteger()),
        sa.Column("yellow_cards", sa.BigInteger()),
        sa.Column("GW", sa.BigInteger()),
    )
    op.create_table(
        "player_gameweek_history_2018_19",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("name", sa.String()),
        sa.Column("assists", sa.BigInteger()),
        sa.Column("attempted_passes", sa.BigInteger()),
        sa.Column("big_chances_created", sa.BigInteger()),
        sa.Column("big_chances_missed", sa.BigInteger()),
        sa.Column("bonus", sa.BigInteger()),
        sa.Column("bps", sa.BigInteger()),
        sa.Column("clean_sheets", sa.BigInteger()),
        sa.Column("clearances_blocks_interceptions", sa.BigInteger()),
        sa.Column("completed_passes", sa.BigInteger()),
        sa.Column("creativity", sa.Float()),
        sa.Column("dribbles", sa.BigInteger()),
        sa.Column("ea_index", sa.BigInteger()),
        sa.Column("element", sa.BigInteger()),
        sa.Column("errors_leading_to_goal", sa.BigInteger()),
        sa.Column("errors_leading_to_goal_attempt", sa.BigInteger()),
        sa.Column("fixture", sa.BigInteger()),
        sa.Column("fouls", sa.BigInteger()),
        sa.Column("goals_conceded", sa.BigInteger()),
        sa.Column("goals_scored", sa.BigInteger()),
        sa.Column("ict_index", sa.Float()),
        sa.Column("influence", sa.Float()),
        sa.Column("key_passes", sa.BigInteger()),
        sa.Column("kickoff_time", sa.String()),
        sa.Column("kickoff_time_formatted", sa.String()),
        sa.Column("loaned_in", sa.BigInteger()),
        sa.Column("loaned_out", sa.BigInteger()),
        sa.Column("minutes", sa.BigInteger()),
        sa.Column("offside", sa.BigInteger()),
        sa.Column("open_play_crosses", sa.BigInteger()),
        sa.Column("opponent_team", sa.BigInteger()),
        sa.Column("own_goals", sa.BigInteger()),
        sa.Column("penalties_conceded", sa.BigInteger()),
        sa.Column("penalties_missed", sa.BigInteger()),
        sa.Column("penalties_saved", sa.BigInteger()),
        sa.Column("recoveries", sa.BigInteger()),
        sa.Column("red_cards", sa.BigInteger()),
        sa.Column("round", sa.BigInteger()),
        sa.Column("saves", sa.BigInteger()),
        sa.Column("selected", sa.BigInteger()),
        sa.Column("tackled", sa.BigInteger()),
        sa.Column("tackles", sa.BigInteger()),
        sa.Column("target_missed", sa.BigInteger()),
        sa.Column("team_a_score", sa.BigInteger()),
        sa.Column("team_h_score", sa.BigInteger()),
        sa.Column("threat", sa.Float()),
        sa.Column("total_points", sa.BigInteger()),
        sa.Column("transfers_balance", sa.BigInteger()),
        sa.Column("transfers_in", sa.BigInteger()),
        sa.Column("transfers_out", sa.BigInteger()),
        sa.Column("value", sa.BigInteger()),
        sa.Column("was_home", sa.Boolean()),
        sa.Column("winning_goals", sa.BigInteger()),
        sa.Column("yellow_cards", sa.BigInteger()),
        sa.Column("GW", sa.BigInteger()),
    )
    op.create_table(
        "player_gameweek_history_2019_20",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String()),
        sa.Column("assists", sa.BigInteger()),
        sa.Column("bonus", sa.BigInteger()),
        sa.Column("bps", sa.BigInteger()),
        sa.Column("clean_sheets", sa.BigInteger()),
        sa.Column("creativity", sa.Float()),
        sa.Column("element", sa.BigInteger()),
        sa.Column("fixture", sa.BigInteger()),
        sa.Column("goals_conceded", sa.BigInteger()),
        sa.Column("goals_scored", sa.BigInteger()),
        sa.Column("ict_index", sa.Float()),
        sa.Column("influence", sa.Float()),
        sa.Column("kickoff_time", sa.String()),
        sa.Column("minutes", sa.BigInteger()),
        sa.Column("opponent_team", sa.BigInteger()),
        sa.Column("own_goals", sa.BigInteger()),
        sa.Column("penalties_missed", sa.BigInteger()),
        sa.Column("penalties_saved", sa.BigInteger()),
        sa.Column("red_cards", sa.BigInteger()),
        sa.Column("round", sa.BigInteger()),
        sa.Column("saves", sa.BigInteger()),
        sa.Column("selected", sa.BigInteger()),
        sa.Column("team_a_score", sa.BigInteger()),
        sa.Column("team_h_score", sa.BigInteger()),
        sa.Column("threat", sa.Float()),
        sa.Column("total_points", sa.BigInteger()),
        sa.Column("transfers_balance", sa.BigInteger()),
        sa.Column("transfers_in", sa.BigInteger()),
        sa.Column("transfers_out", sa.BigInteger()),
        sa.Column("value", sa.BigInteger()),
        sa.Column("was_home", sa.Boolean()),
        sa.Column("yellow_cards", sa.BigInteger()),
        sa.Column("GW", sa.BigInteger()),
    )
    op.create_table(
        "player_gameweek_history_2020_21",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String()),
        sa.Column("position", sa.String()),
        sa.Column("team", sa.String()),
        sa.Column("xP", sa.Float()),
        sa.Column("assists", sa.BigInteger()),
        sa.Column("bonus", sa.BigInteger()),
        sa.Column("bps", sa.BigInteger()),
        sa.Column("clean_sheets", sa.BigInteger()),
        sa.Column("creativity", sa.Float()),
        sa.Column("element", sa.BigInteger()),
        sa.Column("fixture", sa.BigInteger()),
        sa.Column("goals_conceded", sa.BigInteger()),
        sa.Column("goals_scored", sa.BigInteger()),
        sa.Column("ict_index", sa.Float()),
        sa.Column("influence", sa.Float()),
        sa.Column("kickoff_time", sa.String()),
        sa.Column("minutes", sa.BigInteger()),
        sa.Column("opponent_team", sa.BigInteger()),
        sa.Column("own_goals", sa.BigInteger()),
        sa.Column("penalties_missed", sa.BigInteger()),
        sa.Column("penalties_saved", sa.BigInteger()),
        sa.Column("red_cards", sa.BigInteger()),
        sa.Column("round", sa.BigInteger()),
        sa.Column("saves", sa.BigInteger()),
        sa.Column("selected", sa.BigInteger()),
        sa.Column("team_a_score", sa.BigInteger()),
        sa.Column("team_h_score", sa.BigInteger()),
        sa.Column("threat", sa.Float()),
        sa.Column("total_points", sa.BigInteger()),
        sa.Column("transfers_balance", sa.BigInteger()),
        sa.Column("transfers_in", sa.BigInteger()),
        sa.Column("transfers_out", sa.BigInteger()),
        sa.Column("value", sa.BigInteger()),
        sa.Column("was_home", sa.Boolean()),
        sa.Column("yellow_cards", sa.BigInteger()),
        sa.Column("GW", sa.BigInteger()),
    )
    op.create_table(
        "player_gameweek_history_2021_22",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String()),
        sa.Column("position", sa.String()),
        sa.Column("team", sa.String()),
        sa.Column("xP", sa.Float()),
        sa.Column("assists", sa.BigInteger()),
        sa.Column("bonus", sa.BigInteger()),
        sa.Column("bps", sa.BigInteger()),
        sa.Column("clean_sheets", sa.BigInteger()),
        sa.Column("creativity", sa.Float()),
        sa.Column("element", sa.BigInteger()),
        sa.Column("fixture", sa.BigInteger()),
        sa.Column("goals_conceded", sa.BigInteger()),
        sa.Column("goals_scored", sa.BigInteger()),
        sa.Column("ict_index", sa.Float()),
        sa.Column("influence", sa.Float()),
        sa.Column("kickoff_time", sa.String()),
        sa.Column("minutes", sa.BigInteger()),
        sa.Column("opponent_team", sa.BigInteger()),
        sa.Column("own_goals", sa.BigInteger()),
        sa.Column("penalties_missed", sa.BigInteger()),
        sa.Column("penalties_saved", sa.BigInteger()),
        sa.Column("red_cards", sa.BigInteger()),
        sa.Column("round", sa.BigInteger()),
        sa.Column("saves", sa.BigInteger()),
        sa.Column("selected", sa.BigInteger()),
        sa.Column("team_a_score", sa.BigInteger()),
        sa.Column("team_h_score", sa.BigInteger()),
        sa.Column("threat", sa.Float()),
        sa.Column("total_points", sa.BigInteger()),
        sa.Column("transfers_balance", sa.BigInteger()),
        sa.Column("transfers_in", sa.BigInteger()),
        sa.Column("transfers_out", sa.BigInteger()),
        sa.Column("value", sa.BigInteger()),
        sa.Column("was_home", sa.Boolean()),
        sa.Column("yellow_cards", sa.BigInteger()),
        sa.Column("GW", sa.BigInteger()),
    )
    op.create_table(
        "player_gameweek_history_2022_23",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String()),
        sa.Column("position", sa.String()),
        sa.Column("team", sa.String()),
        sa.Column("xP", sa.Float()),
        sa.Column("assists", sa.BigInteger()),
        sa.Column("bonus", sa.BigInteger()),
        sa.Column("bps", sa.BigInteger()),
        sa.Column("clean_sheets", sa.BigInteger()),
        sa.Column("creativity", sa.Float()),
        sa.Column("element", sa.BigInteger()),
        sa.Column("expected_assists", sa.Float()),
        sa.Column("expected_goal_involvements", sa.Float()),
        sa.Column("expected_goals", sa.Float()),
        sa.Column("expected_goals_conceded", sa.Float()),
        sa.Column("fixture", sa.BigInteger()),
        sa.Column("goals_conceded", sa.BigInteger()),
        sa.Column("goals_scored", sa.BigInteger()),
        sa.Column("ict_index", sa.Float()),
        sa.Column("influence", sa.Float()),
        sa.Column("kickoff_time", sa.String()),
        sa.Column("minutes", sa.BigInteger()),
        sa.Column("opponent_team", sa.BigInteger()),
        sa.Column("own_goals", sa.BigInteger()),
        sa.Column("penalties_missed", sa.BigInteger()),
        sa.Column("penalties_saved", sa.BigInteger()),
        sa.Column("red_cards", sa.BigInteger()),
        sa.Column("round", sa.BigInteger()),
        sa.Column("saves", sa.BigInteger()),
        sa.Column("selected", sa.BigInteger()),
        sa.Column("starts", sa.BigInteger()),
        sa.Column("team_a_score", sa.BigInteger()),
        sa.Column("team_h_score", sa.BigInteger()),
        sa.Column("threat", sa.Float()),
        sa.Column("total_points", sa.BigInteger()),
        sa.Column("transfers_balance", sa.BigInteger()),
        sa.Column("transfers_in", sa.BigInteger()),
        sa.Column("transfers_out", sa.BigInteger()),
        sa.Column("value", sa.BigInteger()),
        sa.Column("was_home", sa.Boolean()),
        sa.Column("yellow_cards", sa.BigInteger()),
        sa.Column("GW", sa.BigInteger()),
    )
    op.create_table(
        "player_gameweek_history_2023_24",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String()),
        sa.Column("position", sa.String()),
        sa.Column("team", sa.String()),
        sa.Column("xP", sa.Float()),
        sa.Column("assists", sa.BigInteger()),
        sa.Column("bonus", sa.BigInteger()),
        sa.Column("bps", sa.BigInteger()),
        sa.Column("clean_sheets", sa.BigInteger()),
        sa.Column("creativity", sa.Float()),
        sa.Column("element", sa.BigInteger()),
        sa.Column("expected_assists", sa.Float()),
        sa.Column("expected_goal_involvements", sa.Float()),
        sa.Column("expected_goals", sa.Float()),
        sa.Column("expected_goals_conceded", sa.Float()),
        sa.Column("fixture", sa.BigInteger()),
        sa.Column("goals_conceded", sa.BigInteger()),
        sa.Column("goals_scored", sa.BigInteger()),
        sa.Column("ict_index", sa.Float()),
        sa.Column("influence", sa.Float()),
        sa.Column("kickoff_time", sa.String()),
        sa.Column("minutes", sa.BigInteger()),
        sa.Column("opponent_team", sa.BigInteger()),
        sa.Column("own_goals", sa.BigInteger()),
        sa.Column("penalties_missed", sa.BigInteger()),
        sa.Column("penalties_saved", sa.BigInteger()),
        sa.Column("red_cards", sa.BigInteger()),
        sa.Column("round", sa.BigInteger()),
        sa.Column("saves", sa.BigInteger()),
        sa.Column("selected", sa.BigInteger()),
        sa.Column("starts", sa.BigInteger()),
        sa.Column("team_a_score", sa.BigInteger()),
        sa.Column("team_h_score", sa.BigInteger()),
        sa.Column("threat", sa.Float()),
        sa.Column("total_points", sa.BigInteger()),
        sa.Column("transfers_balance", sa.BigInteger()),
        sa.Column("transfers_in", sa.BigInteger()),
        sa.Column("transfers_out", sa.BigInteger()),
        sa.Column("value", sa.BigInteger()),
        sa.Column("was_home", sa.Boolean()),
        sa.Column("yellow_cards", sa.BigInteger()),
        sa.Column("GW", sa.BigInteger()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("player_gameweek_history_2016_17")
    op.drop_table("player_gameweek_history_2017_18")
    op.drop_table("player_gameweek_history_2018_19")
    op.drop_table("player_gameweek_history_2019_20")
    op.drop_table("player_gameweek_history_2020_21")
    op.drop_table("player_gameweek_history_2021_22")
    op.drop_table("player_gameweek_history_2022_23")
    op.drop_table("player_gameweek_history_2023_24")
