"""removing not null constraint for was_home column

Revision ID: 778c487fa8c9
Revises: recreate_complete_schema
Create Date: 2025-08-28 13:53:20.611081

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "778c487fa8c9"
down_revision: str | Sequence[str] | None = "recreate_complete_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("player_gameweek_history", "was_home", nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("player_gameweek_history", "was_home", nullable=False)
    # ### end Alembic commands ###
