"""all players table

Revision ID: 35e3aec009b9
Revises: d3ac77b7e5e8
Create Date: 2025-08-24 22:29:04.744838

"""

from collections.abc import Sequence
from uuid import uuid4

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35e3aec009b9"
down_revision: str | Sequence[str] | None = "d3ac77b7e5e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "all_players",
        sa.Column("id", sa.Uuid, default=uuid4, primary_key=True),
        sa.Column("name", sa.String, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("all_players")
    # ### end Alembic commands ###
