"""create table for latest season

Revision ID: cc575d3bf1d3
Revises: 7e9a5ba0b64e
Create Date: 2025-08-28 02:08:13.712031

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc575d3bf1d3"
down_revision: str | Sequence[str] | None = "7e9a5ba0b64e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_gameweek_history_2024_25",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("position", sa.String(), nullable=True),
        sa.Column("team", sa.String(), nullable=True),
        sa.Column("xP", sa.Float(), nullable=True),
        sa.Column("assists", sa.Integer(), nullable=True),
        sa.Column("bonus", sa.Integer(), nullable=True),
        sa.Column("bps", sa.Integer(), nullable=True),
        sa.Column("clean_sheets", sa.Integer(), nullable=True),
        sa.Column("creativity", sa.Float(), nullable=True),
        sa.Column("element", sa.Integer(), nullable=True),
        sa.Column("expected_assists", sa.Float(), nullable=True),
        sa.Column("expected_goal_involvements", sa.Float(), nullable=True),
        sa.Column("expected_goals", sa.Float(), nullable=True),
        sa.Column("expected_goals_conceded", sa.Float(), nullable=True),
        sa.Column("fixture", sa.Integer(), nullable=True),
        sa.Column("goals_conceded", sa.Integer(), nullable=True),
        sa.Column("goals_scored", sa.Integer(), nullable=True),
        sa.Column("ict_index", sa.Float(), nullable=True),
        sa.Column("influence", sa.Float(), nullable=True),
        sa.Column("kickoff_time", sa.String(), nullable=True),
        sa.Column("minutes", sa.Integer(), nullable=True),
        sa.Column("modified", sa.String(), nullable=True),
        sa.Column("opponent_team", sa.Integer(), nullable=True),
        sa.Column("own_goals", sa.Integer(), nullable=True),
        sa.Column("penalties_missed", sa.Integer(), nullable=True),
        sa.Column("penalties_saved", sa.Integer(), nullable=True),
        sa.Column("red_cards", sa.Integer(), nullable=True),
        sa.Column("round", sa.Integer(), nullable=True),
        sa.Column("saves", sa.Integer(), nullable=True),
        sa.Column("selected", sa.BigInteger(), nullable=True),
        sa.Column("starts", sa.Integer(), nullable=True),
        sa.Column("team_a_score", sa.Integer(), nullable=True),
        sa.Column("team_h_score", sa.Integer(), nullable=True),
        sa.Column("threat", sa.Float(), nullable=True),
        sa.Column("total_points", sa.Integer(), nullable=True),
        sa.Column("transfers_balance", sa.Integer(), nullable=True),
        sa.Column("transfers_in", sa.Integer(), nullable=True),
        sa.Column("transfers_out", sa.Integer(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("was_home", sa.Boolean(), nullable=True),
        sa.Column("yellow_cards", sa.Integer(), nullable=True),
        sa.Column("GW", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_gameweek_history_2024_25")
    # ### end Alembic commands ###
