"""add foreign key to individual seasonsclar

Revision ID: 7e9a5ba0b64e
Revises: add_foreign_keys_to_all_players
Create Date: 2025-08-25 02:37:06.169131

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e9a5ba0b64e"
down_revision: str | Sequence[str] | None = "add_foreign_keys_to_all_players"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_gameweek_history_2016_17",
        sa.Column("all_player_id", sa.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_player_gameweek_history_2016_17_all_player_id",
        "player_gameweek_history_2016_17",
        "all_players",
        ["all_player_id"],
        ["id"],
    )
    op.add_column(
        "player_gameweek_history_2017_18",
        sa.Column("all_player_id", sa.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_player_gameweek_history_2017_18_all_player_id",
        "player_gameweek_history_2017_18",
        "all_players",
        ["all_player_id"],
        ["id"],
    )
    op.add_column(
        "player_gameweek_history_2018_19",
        sa.Column("all_player_id", sa.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_player_gameweek_history_2018_19_all_player_id",
        "player_gameweek_history_2018_19",
        "all_players",
        ["all_player_id"],
        ["id"],
    )
    op.add_column(
        "player_gameweek_history_2019_20",
        sa.Column("all_player_id", sa.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_player_gameweek_history_2019_20_all_player_id",
        "player_gameweek_history_2019_20",
        "all_players",
        ["all_player_id"],
        ["id"],
    )
    op.add_column(
        "player_gameweek_history_2020_21",
        sa.Column("all_player_id", sa.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_player_gameweek_history_2020_21_all_player_id",
        "player_gameweek_history_2020_21",
        "all_players",
        ["all_player_id"],
        ["id"],
    )
    op.add_column(
        "player_gameweek_history_2021_22",
        sa.Column("all_player_id", sa.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_player_gameweek_history_2021_22_all_player_id",
        "player_gameweek_history_2021_22",
        "all_players",
        ["all_player_id"],
        ["id"],
    )
    op.add_column(
        "player_gameweek_history_2022_23",
        sa.Column("all_player_id", sa.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_player_gameweek_history_2022_23_all_player_id",
        "player_gameweek_history_2022_23",
        "all_players",
        ["all_player_id"],
        ["id"],
    )
    op.add_column(
        "player_gameweek_history_2023_24",
        sa.Column("all_player_id", sa.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_player_gameweek_history_2023_24_all_player_id",
        "player_gameweek_history_2023_24",
        "all_players",
        ["all_player_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_player_gameweek_history_2023_24_all_player_id",
        "player_gameweek_history_2023_24",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_player_gameweek_history_2022_23_all_player_id",
        "player_gameweek_history_2022_23",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_player_gameweek_history_2021_22_all_player_id",
        "player_gameweek_history_2021_22",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_player_gameweek_history_2020_21_all_player_id",
        "player_gameweek_history_2020_21",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_player_gameweek_history_2019_20_all_player_id",
        "player_gameweek_history_2019_20",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_player_gameweek_history_2018_19_all_player_id",
        "player_gameweek_history_2018_19",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_player_gameweek_history_2017_18_all_player_id",
        "player_gameweek_history_2017_18",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_player_gameweek_history_2016_17_all_player_id",
        "player_gameweek_history_2016_17",
        type_="foreignkey",
    )
    op.drop_column("player_gameweek_history_2016_17", "all_player_id")
    op.drop_column("player_gameweek_history_2017_18", "all_player_id")
    op.drop_column("player_gameweek_history_2018_19", "all_player_id")
    op.drop_column("player_gameweek_history_2019_20", "all_player_id")
    op.drop_column("player_gameweek_history_2020_21", "all_player_id")
    op.drop_column("player_gameweek_history_2021_22", "all_player_id")
    op.drop_column("player_gameweek_history_2022_23", "all_player_id")
    op.drop_column("player_gameweek_history_2023_24", "all_player_id")
    # ### end Alembic commands ###
