"""removing not null constraint from gameweek tables

Revision ID: d814d975d80f
Revises: 778c487fa8c9
Create Date: 2025-08-28 14:35:29.065051

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d814d975d80f"
down_revision: str | Sequence[str] | None = "778c487fa8c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("player_gameweek_history_2016_17", "team", nullable=True)
    op.alter_column("player_gameweek_history_2017_18", "team", nullable=True)
    op.alter_column("player_gameweek_history_2018_19", "team", nullable=True)
    op.alter_column("player_gameweek_history_2019_20", "team", nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("player_gameweek_history_2016_17", "team", nullable=False)
    op.alter_column("player_gameweek_history_2017_18", "team", nullable=False)
    op.alter_column("player_gameweek_history_2018_19", "team", nullable=False)
    op.alter_column("player_gameweek_history_2019_20", "team", nullable=False)
    # ### end Alembic commands ###
