"""adding_cost_to_players

Revision ID: 6cfa7c51aaa0
Revises: 55c1bfe77010
Create Date: 2025-08-11 13:18:15.850741

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cfa7c51aaa0"
down_revision: Union[str, Sequence[str], None] = "55c1bfe77010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("now_cost", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "now_cost")
    # ### end Alembic commands ###
