"""initial_fpl_database_setup

Revision ID: ae7f68270204
Revises: 
Create Date: 2025-08-11 12:58:31.602880

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'ae7f68270204'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
