"""add winning goals to 19_20

Revision ID: d3ac77b7e5e8
Revises: ee5b778a29a4
Create Date: 2025-08-24 21:52:53.560140

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3ac77b7e5e8"
down_revision: str | Sequence[str] | None = "ee5b778a29a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_gameweek_history_2019_20",
        sa.Column("winning_goals", sa.BigInteger(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player_gameweek_history_2019_20", "winning_goals")
    # ### end Alembic commands ###
